---
postgresql_extra_conf: |
  archive_command = 'pgbackrest --stanza=backup archive-push %p'
  archive_mode = on
  max_wal_senders = 3
  wal_level = replica

pgbackrest_repos:
  - path: "/atl-main"
    retention-full: "7"
    retention-diff: "3"
    type: azure
    azure-account: atlpgstorage
    azure-container: pgbackrest
    azure-key: somelongkeyhere

pgbackrest_stanzas:
  - name: backup
    pg_config:
      - path: "/var/lib/pgsql/{{ postgresql_version }}/data"
    schedules:
      - backup_type: full
        oncalendar: 'Weekly'

