---
- name: Enable SSL on Workers
  become_user: postgres
  shell: |
    source {{ pgsql.base_dir }}/.bash_profile
    /usr/pgsql-{{ pgsql.major_version }}/bin/pg_autoctl enable ssl --pgdata {{ pgsql.base_dir }}/{{ pgsql.major_version }}/ha --ssl-ca-file '' \
    --ssl-crl-file '' --server-key {{ _ssl.ssl_dir }}/server.key --server-cert {{ _ssl.ssl_dir }}/server.crt --ssl-mode prefer
  register: enable_ssl_workers


- name: Restart PGAutoFailover to Apply Changes of SSL Config
  become: true
  shell: |
    sudo systemctl restart pgautofailover
  register: restart_pgautofailover


