---
postgresql_version: "{{ pgsql.major_version }}"

pgbackrest_owner: postgres
pgbackrest_group: postgres
pgbackrest_local_postgresql: "{{ 'pg' in group_names }}"
# https://pgbackrest.org/user-guide.html#replication

pgbackrest_restore_standby: false
pgbackrest_services_install: true
pgbackrest_timer_enabled: true
pgbackrest_timer_random_delay: 0
pgbackrest_spool_path: "/var/spool/pgbackrest"
pgbackrest_async_archive: false
pgbackrest_async_archive_process_max: 2
pgbackrest_global_config:
  log-level-file: "info"
  log-level-console: "info"
  start-fast: "y"
  delta: "y"
pgbackrest_stanzas: []
  # - name: backup
  #   pg_config:
  #     # Local pg server
  #     - path: "/var/lib/pgsql/{{ postgresql_version }}/data"
  #     # Remote (if using backup-standby=y)
  #     - path: "/var/lib/pgsql/{{ postgresql_version }}/data"
  #       host: "10.0.50.51"
  #       host-user: "postgres"
  #   schedules:
  #     - backup_type: full
  #       oncalendar: 'Weekly'
  #   extra:
  #     backup-standby: "y"
  #   # On standby
  # - name: repl
  #   pg_config:
  #     - path: "/var/lib/pgsql/{{ postgresql_version }}/data"
  #   extra:
  #     recovery-option: "primary_conninfo=host=10.0.50.11 user=replic_user port=5432"


pgbackrest_conf_extra: ""
# pgbackrest_conf_extra: |
#   [global:archive-push]
#   compress-level=3


pgbackrest_repos: []
  # # Backup to Azure Blob
  # - path: "/atl-main"
  #   retention-full: "7"
  #   retention-diff: "3"
  #   type: azure
  #   azure-account: atlpgstorage
  #   azure-container: pgbackrest
  #   azure-key: somelongkeyhere
  # # replication
  # - host: "10.0.50.11"
  #   host-user: "postgres"
