---
# Versions
postgres_release: "{{ pgsql.major_version }}"

# OS User
postgres_user: postgres
postgres_group: postgres

# Packages
repmgr_package: "repmgr_{{ postgres_release }}"
postgresql_server_package: "postgresql{{ postgres_release }}-server,python3-psycopg2"

# Services
repmgr_service: "repmgr{{ postgres_release }}"
postgres_service: "postgresql-{{ postgres_release }}"

# Postgres Vars
repmgr_postgres_admin_user: 'postgres'
repmgr_postgres_admin_user_group: 'postgres'
postgres_ssh_dir: '/var/lib/pgsql/.ssh'
postgres_ssh_rsa_key: "{{ postgres_ssh_dir }}/id_rsa"

# Postgres Vars
postgres_data_directory: "/var/lib/pgsql/{{ postgres_release }}/data"
postgres_conf_directory: "/etc/postgresql/{{ postgres_release }}/data"

# Repmgr Repository
repmgr_install_repository: true
repmgr_repository: "https://dl.2ndquadrant.com/default/release/browse/rpm/packages/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/{{ postgres_release }}"

# Postgresql Repository
postgres_repo_name: "postgres_{{ postgres_release }}"
postgres_repo: "https://ftp.postgresql.org/pub/repos/yum/{{ postgres_release }}/redhat/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"

# Repmgr Vars
repmgr_conf_file: 'repmgr.conf'
repmgr_conf_dir: '/etc/repmgr/{{ postgres_release }}'
repmgr_user: 'repmgr'
repmgr_dbname: 'repmgr'

# Repmgr Config Options
# repmgr_conninfo: "host=127.0.0.1 user={{repmgr_postgres_user}} dbname={{ repmgr_dbname }}"
repmgr_conninfo: "host={{ _ipaddr }} user={{ repmgr_user }} dbname={{ repmgr_dbname }}"
# repmgr_node_id: 1
repmgr_failover: 'automatic'
repmgr_loglevel: 'INFO'
repmgr_logfacility: 'STDERR'
repmgr_log_file: '/var/log/repmgr/repmgr.log'
repmgr_pg_bindir: "/usr/pgsql-{{ postgres_release }}/bin"

# Repmgr Commands
repmgr_promote_command: "/usr/pgsql-{{ postgres_release }}/bin/repmgr standby promote -f /etc/repmgr/{{ postgres_release }}/repmgr.conf --log-to-file"
repmgr_follow_command: "/usr/pgsql-{{ postgres_release }}/bin/repmgr standby follow -f /etc/repmgr/{{ postgres_release }}/repmgr.conf --log-to-file"
repmgr_start_command: "/usr/bin/sudo /usr/bin/systemctl start postgresql-{{ postgres_release }}.service"
repmgr_stop_command: "/usr/bin/sudo /usr/bin/systemctl stop postgresql-{{ postgres_release }}.service"
repmgr_restart_command: "/usr/bin/sudo /usr/bin/systemctl restart postgresql-{{ postgres_release }}.service"

# Role Management
repmgr_is_master: false
repmgr_register_master: false
repmgr_register_standby: false
repmgr_clone_standby: false
repmgr_bootstrap: false
repmgr_install_only: true
repmgr_install_postgresql: false


rh_common_dep_pkgs: "@Development tools,epel-release,perl,perl-libs,firewalld,readline-devel,libicu-devel,rsyslog,rsync,python3,python3-libs,python3-devel,python3-pip,python3-setuptools,python3-rpm-generators,gcc,python3-psycopg2,selinux-policy-targeted"
remove_rh_common_dep_pkgs: "readline-devel,libicu-devel,rsyslog,rsync,python3-setuptools,python3-rpm-generators,python3-PyYAML,python3-pathspec,python3-psycopg2,,epel-release"

rh7_dep_pkgs: "tk"
rh8_dep_pkgs: "tk"
rh9_dep_pkgs: "tk"
rh10_dep_pkgs: "tk"

rh7_python_pkgs: "python-psycopg2"                                      # python3-utils, python3-pathspec
rh8_python_pkgs: "python39,python39-pip,python39-libs,python39-devel"   # python3-psycopg2, python3-PyYAML,
rh9_python_pkgs: "python3.11,python3.11-pip,python3.11-libs,python3.11-devel"
rh10_python_pkgs: "python3.12-pip,python3.12-devel"


delete_file_list:
  - "/var/lib/pgsql/{{ postgres_release }}/{{ pgsql.db_name }}"
  - "/var/lib/pgsql/{{ postgres_release }}/data"
  - "/var/lib/pgsql/{{ postgres_release }}/backup"
  - "/var/lib/pgsql/{{ postgres_release }}/backups"
  - "/var/lib/pgsql/{{ postgres_release }}/.local"
  - "/var/lib/pgsql/{{ postgres_release }}/certs"
  - "/var/lib/pgsql/{{ postgres_release }}"
  - "/etc/systemd/system/postgresql-{{ postgres_release }}.service"
  - "/var/lib/pgsql/postgresql-{{ postgres_release }}.service"
  - "/home/postgres/.local"
  - "/home/postgres/.ansible_async"


