---
# Versions
postgres_release: "{{ pgsql.major_version }}"

# OS User
postgres_user: postgres
postgres_group: postgres

# Packages
# bucardo_package: "bucardo_{{ postgres_release }}"
bucardo_package: "perl-Test-Simple,perl-boolean,perl-ExtUtils-MakeMaker,perl-CGI,perl-DBD-Pg,perl-Encode-Locale,perl-Sys-Syslog"
# bucardo_package: "perl-Test-Simple,perl-boolean,perl-ExtUtils-MakeMaker,perl-CGI,perl-DBD-Pg,perl-Encode-Locale,perl-Pod-Parser,perl-Sys-Syslog"

postgresql_server_package: "postgresql{{ postgres_release }}-libs,postgresql{{ postgres_release }},postgresql{{ postgres_release }}-server,postgresql{{ postgres_release }}-plperl,postgresql{{ postgres_release }}-contrib"


# Services
bucardo_service: "bucardo{{ postgres_release }}"
postgres_service: "postgresql-{{ postgres_release }}"

# Postgres Vars
bucardo_postgres_admin_user: 'postgres'
bucardo_postgres_admin_user_group: 'postgres'
postgres_ssh_dir: '/var/lib/pgsql/.ssh'
postgres_ssh_rsa_key: "{{ postgres_ssh_dir }}/id_rsa"

# Postgres Vars
postgres_data_directory: "/var/lib/pgsql/{{ postgres_release }}/data"
postgres_conf_directory: "/etc/postgresql/{{ postgres_release }}/data"

# bucardo Repository
bucardo_install_repository: true
bucardo_repository: "https://dl.2ndquadrant.com/default/release/browse/rpm/packages/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/{{ postgres_release }}"

# Postgresql Repository
postgres_repo_name: "postgres_{{ postgres_release }}"
postgres_repo: "https://ftp.postgresql.org/pub/repos/yum/{{ postgres_release }}/redhat/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"

# bucardo Vars
bucardo_conf_file: 'bucardo.conf'
bucardo_conf_dir: '/etc/bucardo/{{ postgres_release }}'
bucardo_user: 'bucardo'
bucardo_dbname: 'bucardo'

# bucardo Config Options
# bucardo_conninfo: "host=127.0.0.1 user={{bucardo_postgres_user}} dbname={{ bucardo_dbname }}"
bucardo_conninfo: "host={{ _ipaddr }} user={{ bucardo_user }} dbname={{ bucardo_dbname }}"
# bucardo_node_id: 1
bucardo_failover: 'automatic'
bucardo_loglevel: 'INFO'
bucardo_logfacility: 'STDERR'
bucardo_log_file: '/var/log/bucardo/bucardo.log'
bucardo_pg_bindir: "/usr/pgsql-{{ postgres_release }}/bin"

# bucardo Commands
bucardo_promote_command: "/usr/pgsql-{{ postgres_release }}/bin/bucardo standby promote -f /etc/bucardo/{{ postgres_release }}/bucardo.conf --log-to-file"
bucardo_follow_command: "/usr/pgsql-{{ postgres_release }}/bin/bucardo standby follow -f /etc/bucardo/{{ postgres_release }}/bucardo.conf --log-to-file"
bucardo_start_command: "/usr/bin/sudo /usr/bin/systemctl start postgresql-{{ postgres_release }}.service"
bucardo_stop_command: "/usr/bin/sudo /usr/bin/systemctl stop postgresql-{{ postgres_release }}.service"
bucardo_restart_command: "/usr/bin/sudo /usr/bin/systemctl restart postgresql-{{ postgres_release }}.service"

# Role Management
bucardo_is_master: false
bucardo_register_master: false
bucardo_register_standby: false
bucardo_clone_standby: false
bucardo_bootstrap: false
bucardo_install_only: true
bucardo_install_postgresql: false

#
rh_common_dep_pkgs: "@Development tools,epel-release,perl,perl-libs,firewalld,readline-devel,libicu-devel,rsyslog,rsync,postgresql-devel,
python3,python3-libs,python3-devel,python3-pip,python3-setuptools,python3-rpm-generators,gcc,python3-psycopg2,selinux-policy-targeted"

remove_rh_common_dep_pkgs: "readline-devel,libicu-devel,rsyslog,rsync,postgresql-devel,python3-setuptools,python3-rpm-generators,python3-PyYAML,
python3-pathspec,python3-psycopg2,,epel-release"

rh7_dep_pkgs: "tk"
rh8_dep_pkgs: "tk"
rh9_dep_pkgs: "tk"

rh7_python_pkgs: "python-psycopg2"
# python3-utils, python3-pathspec

rh8_python_pkgs: "python39,python39-pip,python39-libs,python39-devel"
# python3-psycopg2, python3-PyYAML,

rh9_python_pkgs: "python3.11,python3.11-pip,python3.11-libs,python3.11-devel"

delete_file_list:
  - "/var/lib/pgsql/{{ postgres_release }}/{{ pgsql.db_name }}"
  - "/var/lib/pgsql/{{ postgres_release }}/data"
  - "/var/lib/pgsql/{{ postgres_release }}/backup"
  - "/var/lib/pgsql/{{ postgres_release }}/backups"
  - "/var/lib/pgsql/{{ postgres_release }}/.local"
  - "/var/lib/pgsql/{{ postgres_release }}/certs"
  - "/etc/systemd/system/postgresql-{{ postgres_release }}.service"
  - "/var/lib/pgsql/postgresql-{{ postgres_release }}.service"
  - "/home/postgres/.local"
  - "/home/postgres/.ansible_async"

