---
- name: Register Primary Node
  become_user: "{{ repmgr_postgres_admin_user }}"
  shell: |
    /usr/pgsql-{{ postgres_release }}/bin/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} primary register
  register: register_primary_node


#- name: Ensure Repmgrd is Started
#  service:
#    name: "{{ repmgr_service }}"
#    state: started
#    enabled: true


- name: Check the Status of the Repmgr Cluster
  become_user: "{{ repmgr_postgres_admin_user }}"
  shell: |
    /usr/pgsql-{{ postgres_release }}/bin/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} cluster show
  register: check_cluster_status
- debug: msg={{ check_cluster_status }}

