---
- name: Unregister Witness Node
  become_user: "{{ repmgr_postgres_admin_user }}"
  shell: |
    /usr/pgsql-{{ postgres_release }}/bin/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} witness unregister
  register: unregister_witness_node
  ignore_errors: true


- name: Check the Status of the Repmgr Cluster
  become_user: "{{ repmgr_postgres_admin_user }}"
  shell: |
    /usr/pgsql-{{ postgres_release }}/bin/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} cluster show
  register: check_cluster_status
  ignore_errors: true
- debug: msg={{ check_cluster_status }}

