---
- name: Waiting for Server to Come Back After Restart
  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started delay=10 timeout=300 connect_timeout=300 search_regex=OpenSSH
  become: no


- name: Restart System
  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible Updates Triggered" ) &
  async: 30
  poll: 0


- name: Stop Postgresql
  service:
    name: "{{ postgres_service }}"
    state: stopped


- name: Start Postgresql
  service:
    name: "{{ postgres_service }}"
    state: started


- name: Restart Postgresql
  service:
    name: "{{ postgres_service }}"
    state: restarted


- name: Reload Postgresql
  service:
    name: "{{ postgres_service }}"
    state: reloaded

