---
- name: Verify the State of Postgres Instance
  become_user: postgres
  shell: |
    source {{ pgsql.base_dir }}/.bash_profile
    /usr/pgsql-{{ pgsql.major_version }}/bin/pg_ctl -V
  register: verify_single_postgres_state
  args:
    chdir: "{{ pgsql.base_dir }}"
    executable: /bin/bash


- debug: msg={{ verify_single_postgres_state }}
  become_user: postgres
  tags: print_debug


