---
- name: Install EPEL Package Repository
  package:
    name: epel-release
    state: present
  register: install_epel_pkg_repo
- debug: msg={{ install_epel_pkg_repo }}
  when: print_debug == true


- name: Enable PGDG PostgreSQL Repository
  dnf:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present
    disable_gpg_check: true
  register: enable_pgdb_pgsql_repo
- debug: msg={{ enable_pgdb_pgsql_repo }}
  when: print_debug == true


- name: Enable PostgreSQL Common Repository
  yum_repository:
    name: "pgsql-{{ pgsql.major_version }}-common-repo"
    description: PostgreSQL Common Repository
    baseurl: "https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-{{ ansible_distribution_major_version }}-x86_64/"
    state: present
    gpgcheck: no


- name: Download and Install GPG Key
  rpm_key:
    state: present
    key: https://ftp.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL


- name: Update DNF cache
  dnf:
    update_cache: yes
  register: update_dnf_cache
- debug: msg={{ update_dnf_cache }}
  when: print_debug == true


