---
- name: Uninstall PostgreSQL RPM Package
  package:
    name: "{{ item }}"
    state: absent
    disable_gpg_check: true
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"
  with_items:
    - postgresql{{ pgsql.major_version }}-server
    - postgresql{{ pgsql.major_version }}
    - libpq5


- name: Delete Configuration Files and Data Directory for PGDG Postgres
  file:
    path: "{{ item }}"
    state: absent
  register: delete_postgres_config_files
  with_items: "{{ delete_file_list }}"


- debug: msg="{{ rh_uninstall_pkgs }}"


- name: Uninstall Prerequesties RPM Packages for PGDG Postgres
  dnf:
    name: "{{ rh_uninstall_pkgs }}"
    state: absent
    # skip_broken: yes
  vars:
    ansible_python_interpreter: "{{ yum_python_version }}"


- name: Reload Systemd Daemon
  systemd:
    daemon_reload: yes
  register: reload_sysemd_daemon
  async: 60
  poll: 5


- name: Alternative Python Version
  shell: |
    /usr/sbin/update-alternatives --install /usr/bin/python python {{ yum_python_version }} 1
    /usr/sbin/alternatives --set python {{ yum_python_version }}
  register: alternatives_python3
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'


