---
- name: Install Bucardo
  become_user: postgres
  shell: |
    echo P | /usr/local/bin/bucardo install
  register: install_bucardo
  ignore_errors: true
  args:
    executable: /bin/bash
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['primary']
- debug: msg={{ install_bucardo }}
  when: inventory_hostname in groups['primary']


- name: Add the Source DB to Configure Bucardo
  become_user: postgres
  shell: |
    bucardo add database {{ tdb_name }} dbname={{ _bucardo.dbinfo[0].db_name }} host={{ ansible_ssh_host }}
  register: add_source_db
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['primary']
- debug: msg={{ add_source_db }}
  when: inventory_hostname in groups['primary']


- name:  Add Destination DB
  become_user: postgres
  shell: |
    bucardo add database {{ tdb_name }} dbname={{ _bucardo.dbinfo[0].db_name }} host={{ ansible_ssh_host }}
  register: add_destination_db
  delegate_to: "{{ hostvars[groups['primary'][0]]['ansible_hostname'] }}"
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['secondary']
- debug: msg={{ add_destination_db }}
  when: inventory_hostname in groups['secondary']


- name: Add the table schema to replicate
  become_user: postgres
  shell: |
    bucardo add table public.users db={{ tdb_name }}
  register: add_table_schema
  delegate_to: "{{ hostvars[groups['primary'][0]]['ansible_hostname'] }}"
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['all']
- debug: msg={{ add_table_schema }}
  when: inventory_hostname in groups['all']


- name: Add all Tables on the Database
  become_user: postgres
  shell: |
    bucardo add all tables --her={{ her_name }} db={{ tdb_name }}
  register: add_all_tables
  delegate_to: "{{ hostvars[groups['primary'][0]]['ansible_hostname'] }}"
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['all']
- debug: msg={{ add_all_tables }}
  when: inventory_hostname in groups['all']


- name: List the Relgroup
  become_user: postgres
  shell: |
    bucardo list relgroup
  register: list_relgroup
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['primary']
- debug: msg={{ list_relgroup }}
  when: inventory_hostname in groups['primary']


- name: Build a Sync
  become_user: postgres
  shell: |
    bucardo add sync {{ her_name }} relgroup={{ relgroup }} db={{ db_list }}
  register: build_sync
  delegate_to: "{{ hostvars[groups['primary'][0]]['ansible_hostname'] }}"
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['all']
- debug: msg={{ build_sync }}
  when: inventory_hostname in groups['all']


- name: List the Sync to See if It is Set
  become_user: postgres
  shell: |
    bucardo list sync
  register: list_sync
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['primary']
- debug: msg={{ list_sync }}
  when: inventory_hostname in groups['primary']


- name: Restart the Sync
  become_user: postgres
  shell: |
    bucardo restart sync
  register: restart_sync
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['primary']
- debug: msg={{ restart_sync }}
  when: inventory_hostname in groups['primary']


- name: Status Bucardo for Sync
  become_user: postgres
  shell: |
    bucardo status
  register: status_bucardo_sync
  args:
    executable: /bin/bash
    chdir: /home/postgres
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when: inventory_hostname in groups['primary']
- debug: msg={{ status_bucardo_sync }}
  when: inventory_hostname in groups['primary']


