---
- name: Create a New Table Users
  become_user: postgres
  postgresql_query:
    db: "{{ item }}"
    login_host: "{{ inventory_hostname }}"
    login_user: "{{ _bucardo.db_user }}"
    login_password: "{{ _bucardo.db_password }}"
    query: "CREATE TABLE users (
        id SERIAL PRIMARY KEY,
        first_name VARCHAR(255),
        last_name VARCHAR(255) NOT NULL,
        city VARCHAR(255)
      );"
  register: create_new_table_users
  ignore_errors: true
  with_items:
    - "{{ _bucardo.dbinfo[0].db_name }}"
- debug: msg={{ create_new_table_users }}


- name: Verify the List of Available Data on the Table
  become_user: postgres
  postgresql_query:
    db: "{{ item }}"
    login_host: "{{ inventory_hostname }}"
    login_user: "{{ _bucardo.db_user }}"
    login_password: "{{ _bucardo.db_password }}"
    query: "select * from users;"
  register: verify_list_available_data
  ignore_errors: true
  with_items:
    - "{{ _bucardo.dbinfo[0].db_name }}"
- debug: msg={{ verify_list_available_data }}


- name: Create Table in Postgresql Bucardo Database
  become_user: postgres
  postgresql_query:
    db: "{{ _bucardo.dbinfo[0].db_name }}"
    login_host: "{{ inventory_hostname }}"
    login_user: "{{ _bucardo.db_user }}"
    login_password: "{{ _bucardo.db_password }}"
    query: "{{ item }}"
  register: verify_list_available_data
  with_items:
    - "CREATE EXTENSION plperl;"
    - "CREATE SCHEMA bucardo;"
- debug: msg={{ verify_list_available_data }}

