---
- name: Ensure PostgreSQL Repository
  yum_repository:
    name: "{{ postgres_repo_name }}"
    description: PostgreSQL repository
    baseurl: "{{ postgres_repo }}"


- name: Download and Install GPG Key
  rpm_key:
    state: present
    key: https://ftp.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL


- name: Ensure PostgreSQL Packages are Installed
  yum:
    name: "{{ postgresql_server_package }}"
    state: present
    enablerepo: "{{ postgres_repo_name }}"


- name: Install Bucardo Packages
  yum:
    name: "{{ bucardo_package }}"
    state: present

