---
- name: Uninstall bucardo Packages
  yum:
    name: "{{ bucardo_package }}"
    state: present


- name: Uninstall PostgreSQL Packages
  yum:
    name: "{{ postgresql_server_package }}"
    state: absent
    enablerepo: "{{ postgres_repo_name }}"

