---
- name: Waiting for Server to Come Back After Restart
  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started delay=10 timeout=300 connect_timeout=300 search_regex=OpenSSH
  become: no


- name: Restart System
  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible Updates Triggered" ) &
  async: 30
  poll: 0


- name: Restart HAPproxy Service
  systemd:
    daemon_reload: true
    name: haproxy
    enabled: true
    state: restarted
  listen: "Restart HAPproxy"


- name: Check HAProxy is Started and Accepting Connections
  wait_for:
    port: 7000
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    state: started
    timeout: 120
    delay: 10
  ignore_errors: false
  listen: "Restart HAProxy"


- name: Restart Keepalived
  systemd: name=keepalived state=restarted


- name: Restart Network
  systemd: name=network state=restart

