rh_common_dep_pkgs: "@Development tools,epel-release,perl,perl-libs,firewalld,readline-devel,libicu-devel,rsyslog,rsync,python3,python3-libs,python3-devel,python3-pip,python3-setuptools,python3-rpm-generators,gcc"
remove_rh_common_dep_pkgs: "readline-devel,libicu-devel,rsyslog,rsync,python3-setuptools,python3-rpm-generators,python3-PyYAML,gcc,epel-release"
# python3-pathspec,python3-psycopg2,


rh7_dep_pkgs: "tk"
# python-psycopg2,etcd,yamllint"
rh8_dep_pkgs: "tk"
rh9_dep_pkgs: "tk"
rh10_dep_pkgs: "tk"


rh7_python_pkgs: "python-psycopg2"
# python3-PyYAML,python3-psycopg2,
rh8_python_pkgs: "python39,python39-pip,python39-libs,python39-devel"
# python3-pathspec"
rh9_python_pkgs: "python3.11,python3.11-pip,python3.11-libs,python3.11-devel"
rh10_python_pkgs: "python3.12-pip,python3.12-devel"


# - "setuptools-rust"
common_pip3_module:
  - "cdiff"
  - "typing"
  - "wheel"
  - "setuptools=={{ setuptools_version }}"
  - "-r /var/lib/pgsql/requirements.txt"


# Prerequesties for Patroni
prereq_pip3_module:
  - "tzlocal"
  - "requests"
  - "ydiff"
  - "psutil"
  - "prettytable"
  - "click"
  - "python-etcd"
  - "psycopg"
#  - "psycopg2"


pg13_pip3_module:
  - { pg_ver: 13, cond: "<=", pip3_name: "psycopg2-binary" }


pg14_pip3_module:
  - { pg_ver: 14, cond: ">=", pip3_name: "pyopenssl" }
  - { pg_ver: 14, cond: ">=", pip3_name: "pyrsistent==0.16.0" }


# For patroni
rh8_pip3_module:
  - "patroni==3.0.4"


# For patroni
rh9_pip3_module:
  - "patroni==3.0.4"


rh10_pip3_module:
  - "patroni==3.0.4"


# Versions
postgres_release: "{{ pgsql.major_version }}"


# OS User
postgres_user: postgres
postgres_group: postgres


# Packages
postgresql_server_package: "postgresql{{ postgres_release }}-server"


# Services
postgres_service: "postgresql-{{ postgres_release }}"


# Postgres Vars
postgres_admin_user: 'postgres'
postgres_admin_user_group: 'postgres'
postgres_ssh_dir: '/var/lib/pgsql/.ssh'
postgres_ssh_rsa_key: "{{ postgres_ssh_dir }}/id_rsa"


# Postgres Vars
postgres_data_directory: "/var/lib/pgsql/{{ postgres_release }}/data"
postgres_conf_directory: "/etc/postgresql/{{ postgres_release }}/data"

# Postgresql Repository
# postgres_repo_name: "postgres_{{ postgres_release }}"
# postgres_repo: "https://ftp.postgresql.org/pub/repos/yum/{{ postgres_release }}/redhat/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"
# postgres_repo: "https://download.postgresql.org/pub/repos/yum/{{ postgres_release }}/redhat/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}"


