---
- name: Disable SSL on Workers
  become_user: postgres
  shell: |
    export PGDATA={{ pgsql.base_dir }}/{{ pgsql.major_version }}/ha
    /usr/pgsql-{{ pgsql.major_version }}/bin/pg_autoctl disable ssl
  register: enable_ssl_workers
  ignore_errors: true


- name: Restart PGAutoFailover Service to Apply SSL Changes
  become_user: postgres
  shell: |
    sudo systemctl restart pgautofailover
  register: restart_pgautofailover
  ignore_errors: true

